spring.application.name=AllMart

spring.datasource.url=${NEON_URL}
spring.datasource.username=${NEON_USERNAME}
spring.datasource.password=${NEON_PASSWORD}

spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

allmart.app.jwtSecret=${JWT_SECRET}
allmart.app.jwtExpirationMs=86400000

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

stripe.api.key=${STRIPE_SECRET_API_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.cors.allowed-origins=${FRONTEND_URL:http://localhost:4200}